# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "joey"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Waseem Ahmad"]
  s.date = "2012-04-20"
  s.description = "Object wrappers for nodes in the Facebook OpenGraph"
  s.email = "talk.to.waseem@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "lib/joey.rb",
    "lib/joey/action.rb",
    "lib/joey/affiliation.rb",
    "lib/joey/album.rb",
    "lib/joey/comment.rb",
    "lib/joey/education.rb",
    "lib/joey/education_history.rb",
    "lib/joey/fetching_array.rb",
    "lib/joey/hs_info.rb",
    "lib/joey/image.rb",
    "lib/joey/like.rb",
    "lib/joey/location.rb",
    "lib/joey/model.rb",
    "lib/joey/page.rb",
    "lib/joey/parser_helpers.rb",
    "lib/joey/photo.rb",
    "lib/joey/post.rb",
    "lib/joey/privacy.rb",
    "lib/joey/profile.rb",
    "lib/joey/property.rb",
    "lib/joey/relative.rb",
    "lib/joey/rest_api.rb",
    "lib/joey/status.rb",
    "lib/joey/tag.rb",
    "lib/joey/television.rb",
    "lib/joey/user.rb",
    "lib/joey/version.rb",
    "lib/joey/video.rb",
    "lib/joey/work.rb",
    "lib/joey/work_history.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/joey"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Ruby Wrapper API for Facebook OpenGraph"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.3"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.3"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.3"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

